def get_error_details():
	return (2, 'описание ошибки №2')

errnum, errstr = get_error_details()
print(errnum)
print(errstr)
